id: P009491
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 19:41:11.413002
source_metadata:
  id: bdr:W27324
  title: ནང་བསྟན་མདོ་སྔགས་རྒྱ་མཚོ་ལས་ལག་ཏུ་ལེན་བདེ་བ་གསེར་གྱི་ཐིགས་པ
  author: ''
  volumes:
    e4f802969a414e30891abca4b20d39a0:
      image_group_id: I01JW22
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
